name: Build

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          tags: inikolaev/gha-buildx-docker-build:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
